export const photos = [
  {
    id: 2,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0548.JPG', 
    likes: 0,
    description: 'Barbre Family',
    date: '2021-04-19',
    comments: [
      {
        user: 'Zach',
        comment: ':)',
      },
      {
        user: 'Garion', 
        comment: 'LOVE HER!'
      }
    ],
  },
  {
    id: 3,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0544.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 4,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0539.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 5,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0537.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 6,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0521.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 7,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0517.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 8,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0509.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 9,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0500.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 10,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0499.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 11,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0493.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 13,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0488.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 14,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0485.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 15,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0481.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
  {
    id: 16,
    url: 'https://barbrephotos.nyc3.cdn.digitaloceanspaces.com/IMG_0475.JPG', 
    likes: 0,
    description: '',
    date: '',
    comments: [],
  },
]